//addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M4")
//addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.3.4")
addSbtPlugin("org.duhemm" % "sbt-errors-summary" % "0.6.0")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.0.0-M10")
addSbtPlugin("net.vonbuchholtz" % "sbt-dependency-check" % "0.2.6")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")
addSbtPlugin("com.orrsella" % "sbt-stats" % "1.0.7")
